### ISSUE TITLE
add models supported in Documentation 

### ISSUE THREAD

**Issue by blademckain** [elad-bar/DahuaVTO2MQTT#1]
You could add supported models in the documentation ?

and it would be nice if you could also insert the known firmware versions that are working

**Comment by elad-bar** [comment]
Added SupportedModels.md,
Please add your model and do a pull request

thanks

**Comment by tgebarowski** [comment]
Hi,
I have tested your script and it seems to work with Dahua VTO3211D-P2-S1. I've just opened a PR:
https://github.com/elad-bar/DahuaVTO2MQTT/pull/5

Good work with the script, I really appreciate it.

**Comment by maury77** [comment]
can you support VTO2000A with firmware no sip?

**Comment by elad-bar** [comment]
@maury77 did you try and it didn't work?

Thanks

**Comment by maury77** [comment]
I haven't tried yet

was a question, but if i can i could install your solution.
I don't know if the SIP protocol is needed to activate it

**Comment by elad-bar** [comment]
@maury77 this integration supports publishing events from the unit, not related to SIP communication,
please try and share with us if it works for you

thanks
