### ISSUE TITLE
PHP Notice:  fwrite(): send of X bytes failed with errno=32 Broken pipe in

### ISSUE THREAD

**Issue by KrzysztofKowalczyk74** [elad-bar/DahuaVTO2MQTT#10]
After few messages arriving MQTT broker communication stops and "PHP Notice:  fwrite(): send of X bytes failed with errno=32 Broken pipe in" appears in the log. App started manualy: "php -f DahuaEventHandler.php", environment set as required, system: ubuntu, Home Assistant runs in docker.

<*** Dahua VTO Event Listener START ***>
Device Type: VTO2000A-2
Serial Number: xxxxxxxxxxxxxxxx
**PHP Notice:  Undefined offset: 1 in /home/krzysiek/Dahua/DahuaEventHandler.php on line 509**
Start login
Login success
Started keepAlive thread
keepAlive back
Event Manager subscription reply
Event SIPRegisterResult, Success
MQTT message published, Topic: DahuaVTO/SIPRegisterResult/Event, Payload: {"Action":"Pulse","Data":{"Date":"18-10-2020 17:26:19","LocaleTime":"2020-10-18 17:26:19","Success":true,"UTC":1603038379},"deviceType":"VTO2000A-2","serialNumber":"xxxxxxxxxxxxxxxx"}
Event TimeChange, BeforeModifyTime: 18-10-2020 17:26:49, ModifiedTime: 18-10-2020 17:26:48
MQTT message published, Topic: DahuaVTO/TimeChange/Event, Payload: {"Action":"Pulse","Data":{"BeforeModifyTime":"18-10-2020 17:26:49","LocaleTime":"2020-10-18 17:26:49","ModifiedTime":"18-10-2020 17:26:48","UTC":1603038409},"deviceType":"VTO2000A-2","serialNumber":"xxxxxxxxxxxxxxxx"}
Event NTPAdjustTime with 200.160.0.8 success
MQTT message published, Topic: DahuaVTO/NTPAdjustTime/Event, Payload: {"Action":"Pulse","Data":{"Address":"200.160.0.8","Before":"18-10-2020 17:26:48","LocaleTime":"2020-10-18 17:26:49","UTC":1603038409,"result":true},"deviceType":"VTO2000A-2","serialNumber":"xxxxxxxxxxxxxxxx"}
keepAlive back
Event SIPRegisterResult, Success
**PHP Notice:  fwrite(): send of 3 bytes failed with errno=32 Broken pipe in /home/krzysiek/Dahua/phpMQTT.php on line 270
PHP Notice:  fwrite(): send of 216 bytes failed with errno=32 Broken pipe in /home/krzysiek/Dahua/phpMQTT.php on line 271**

**Comment by elad-bar** [comment]
it seems that you are working with outdated version, can you please update and report back if it still happens?

thanks

**Comment by elad-bar** [comment]
Please check with the latest, ported the docker to python

Thanks
