### ISSUE TITLE
Cannot update to 1.0.7

### ISSUE THREAD

**Issue by mmnpkf** [elad-bar/DahuaVTO2MQTT#11]
Update to 1.0.7 (from 1.0.6, which won’t start) fails:

`20-10-25 00:26:56 INFO (SyncWorker_1) [supervisor.docker.interface] Updateing image 26703e67/amd64-addon-dahuavto2mqtt:1.0.6 to 26703e67/amd64-addon-dahuavto2mqtt:1.0.7
20-10-25 00:26:56 INFO (SyncWorker_1) [supervisor.docker.addon] Starting build for 26703e67/amd64-addon-dahuavto2mqtt:1.0.7
20-10-25 00:27:23 ERROR (SyncWorker_1) [supervisor.docker.addon] Can't build 26703e67/amd64-addon-dahuavto2mqtt:1.0.7: The command '/bin/ash -o pipefail -c apk add --no-cache --update argon2-libs php php-json &&     apk add --no-cache --virtual .build-dependencies git &&     apk add --update libzip-dev curl-dev &&     docker-php-ext-install curl &&     apk del gcc g++ &&    rm -rf /var/cache/apk/* &&     git clone https://github.com/elad-bar/DahuaVTO2MQTT.git --branch ${DAHUA_BRANCH} --depth 1 /app &&     chmod +x /app/DahuaVTO.php &&     apk del .build-dependencies' returned a non-zero code: 14 `

**Comment by elad-bar** [comment]
Please open the issue in the right repo,
This bug related to the addon, not the original docker

Link:
https://github.com/elad-bar/Hassio-addons

Thanks
