### ISSUE TITLE
I can't add the repository

### ISSUE THREAD

**Issue by emorosgit** [elad-bar/DahuaVTO2MQTT#14]
20-10-29 18:27:11 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/elad-bar/DahuaVTO2MQTT repository
20-10-29 18:27:13 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/71317b4c/repository.json: [Errno 2] No such file or directory: '/data/addons/git/71317b4c/repository.json'
20-10-29 18:27:13 ERROR (MainThread) [supervisor.store] https://github.com/elad-bar/DahuaVTO2MQTT is not a valid add-on repository. 
20-10-29 18:27:13 INFO (MainThread) [supervisor.store.git] Removing custom add-on repository https://github.com/elad-bar/DahuaVTO2MQTT

**Comment by elad-bar** [comment]
Please read the readme, this repo is the docker repo,
Addon repo is elad-bar/hassio-addons.

Please note that currently, the repo is not working well, I'm not maintaining it (as I'm working with core version of HA), I hope that someone will take it for maintenance so you will be able to use it,
In the meantime,  I suggest to use the docker version according to the readme
