### ISSUE TITLE
Error after instalation

### ISSUE THREAD

**Issue by ngreis** [elad-bar/DahuaVTO2MQTT#2]
I installed the repository and the addon and i get the following erros on load.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: DahuaVTO2MQTT
 Listens to events from Dahua VTO unit and publishes them via MQTT Message
-----------------------------------------------------------
 **Add-on version: 1.0.5
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
parse error: Expected string key before ':' at line 1, column 4
[15:51:14] ERROR: Unknown HTTP error occured**
 System:   (amd64 / qemux86-64)
 Home Assistant Core: 0.112.4
 Home Assistant Supervisor: 228
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
```

After the log shows that the addon connected to the device and i have MQTT messages on the MQTT broker.
I dont have any binary_sensors nor services to open doors and to get incoming calls from the VTO.

**Comment by elad-bar** [comment]
Hi, you have opened a bug for the addon in repository of docker,
Please report this issue in the right thread of home assistant forum, or try switching to docker (hassio addon is not being maintained anymore)

Thanks

**Comment by ngreis** [comment]
Yes the addon does not have issue tab, :P
I installed the docker now in Unraid, and i get no errors, but i see no services in home assistant, just que mqtt topics appearing in the logs.
In Ha do i have to create the sensors from the MQTT json payload? How do i order the lock to open via MQTT?

**Comment by elad-bar** [comment]
It publishes MQTT messages upon events, 
Listen to the events and react accordingly,
I care just about the invite / access control events,
Wrote automation for that

I'm using NodeRED, with that you can create / update sensors as well

**Comment by ngreis** [comment]
Ok, i have to create automations or NR flows!
Cool, thx for the anwser.

The errors on the addon, dont stop the MQTT from working, so i will revert back to it.
Keep all things in one place, instead of distribuiting via many places.

Once again thx for the reply
