### ISSUE TITLE
Add compatibility with VTO2202F-P

### ISSUE THREAD

**Issue by MPAndrew** [elad-bar/DahuaVTO2MQTT#22]
Hello. Thank you for yout add-on. Can you add compatibility with VTO2202F-P? I think VTO2202F-P is very similar to VTO2000A.
Regards.

**Comment by elad-bar** [comment]
Just to make sure, did you try it and would like me to add it to the list of known working devices list or didn't try it because it's not there?

Thanks

**Comment by MPAndrew** [comment]
I bought it today so I don't have it yet. I will try it when I receive it and if you want I will give you feedback.

Thanks.

**Comment by Margriko** [comment]
Working fine with mine VTO2202F-P
