### ISSUE TITLE
Home Assistant integration plugin

### ISSUE THREAD

**Issue by myhomeiot** [elad-bar/DahuaVTO2MQTT#23]
Since you already ported your gateway to Python is it will be a great idea to have regular Home Assistant integration?
Sure MQTT gateway can be used by different home automation systems, but specially for Home Assistant the [integration plugin](https://developers.home-assistant.io/docs/creating_integration_file_structure) will be much easy to use.

One more question: I have Dahua VTO and as I can see from documentation I can have doorbell sensor, the question is, using this gateway I can only receive events from VTO or can send commands as well? I'm interesting to send command to open the lock.
Thanks in advance!

**Comment by elad-bar** [comment]
thanks for the input, 
I'm currently using NodeRED as integration to that docker over MQTT, the same can be done with automation of HA.

Of course anything that has communication channel can potentially switched into component, but the question is, what is the benefit of it as an HA component, given someone will need to maintain it.

Given the ring is an event, what will turn it off? 
is it just 30 seconds afterwards? or should it wait for opposite event of answering / not answered? opening the gate can be a service for sure, the lights on can be also binary sensor (not sure what will be the benefit of it as well).

thanks

**Comment by myhomeiot** [comment]
Thanks for explanation!
Main benefits having it as integration of HA, less complexity, better reliability but if you currently use it as MQTT it's will require more work to maintain.

Latest versions of HA has [blueprints](https://www.home-assistant.io/docs/automation/using_blueprints/) which make this kind of automation less complex.

Is it possible to send commands to VTO or Dahua API allow only to receive information?

**Comment by elad-bar** [comment]
For now, only retrives information, planning to add MQTT for action, first will be to open gate

**Comment by elad-bar** [comment]
@myhomeiot added the topic [MQTT_BROKER_TOPIC_PREFIX]/Command/Open

**Comment by elad-bar** [comment]
Is it still relevant?

**Comment by myhomeiot** [comment]
@elad-bar Thanks for door open command!
I was thinking that this command should be issued using existing Dahua connection. Because it's simple http command, I did it using shell_command using curl.

I will definitely start using DahuaVTO2MQTT when I will get good reason to install MQTT, currently all automation's which I have  doesn't use it.
