### ISSUE TITLE
Need some help in order to use this over the portainer

### ISSUE THREAD

**Issue by nunokaneco** [elad-bar/DahuaVTO2MQTT#24]
Hello To all

I'm trying to use this in the portainer over the integration in to Home Assistant, but I'm a new user and I nedd some help or a little tutorial to install and use this. 

Can anyone please help me in order to put this to work ?

Thank you in advance for your help I appreciate

**Comment by elad-bar** [comment]
Please review the README, it invlude docker compose to run with all the relevant parameters 

Please let me know if it worked for you

**Comment by nunokaneco** [comment]
> Please review the README, it invlude docker compose to run with all the relevant parameters
> 
> Please let me know if it worked for you

Hello Can you please let me know if this is correct can I still adding the  environment variable in fault and click into deploy the stack ?

![image](https://user-images.githubusercontent.com/33290686/105392351-043a5d80-5c13-11eb-8e8a-0b6c72e93884.png)

Thank you for your support

**Comment by elad-bar** [comment]
you need to replace the environment variables in the docker compose and avoid adding additinal in the section below it

**Comment by nunokaneco** [comment]
> you need to replace the environment variables in the docker compose and avoid adding additinal in the section below it

Great thank you, Done. I also have the MQQT mosquito installed and configured. Now can you please let me know how to receive/configure or test this in the Home Assistant ? 

Once again thank you for your support

**Comment by elad-bar** [comment]
You need to create MQTT sensor or listen to events and trigger automation

**Comment by elad-bar** [comment]
Please read in HA forum, there are few examples

**Comment by nunokaneco** [comment]
> Please read in HA forum, there are few examples

Hello again 

Can you please confirm if is something like this? 

``
sensor:
  - platform: mqtt
    name: "DahuaVTO Event"
    state_topic: "DahuaVTO/CallNoAnswered/Event"
    value_template: "{{ value_json.Action }}"

``

Thank you and best regards

**Comment by elad-bar** [comment]
Should work, in case you need to set up it to work in HA, please post there, I'm sure there are enough examples over there,
Thanks
