### ISSUE TITLE
Install on Hassio

### ISSUE THREAD

**Issue by tnTano** [elad-bar/DahuaVTO2MQTT#25]
hi, i feel like a stupid but in my HA installation (rpi4 with hassio) and i cannot install your repo, nothing from add-on and nothing from HACS, i try with portainer but  don't know hot to modify the image config for the mqtt and vto settings

thanks for the help

**Comment by tnTano** [comment]
ok, in portainer i edit the dockerfile like this:

```
FROM python:3.9-alpine
MAINTAINER Elad Bar <elad.bar@hotmail.com>

WORKDIR /app

RUN wget -P ./ https://raw.githubusercontent.com/elad-bar/DahuaVTO2MQTT/master/Messages.py
RUN wget -P ./ https://raw.githubusercontent.com/elad-bar/DahuaVTO2MQTT/master/DahuaVTO.py

RUN apk update && \
    apk upgrade && \
    pip install paho-mqtt requests
    
ENV DAHUA_VTO_HOST=vto-host
ENV DAHUA_VTO_USERNAME=Username
ENV DAHUA_VTO_PASSWORD=Password
ENV MQTT_BROKER_HOST=mqtt-host
ENV MQTT_BROKER_PORT=1883
ENV MQTT_BROKER_USERNAME=Username
ENV MQTT_BROKER_PASSWORD=Password 
ENV MQTT_BROKER_TOPIC_PREFIX=DahuaVTO
ENV DEBUG=False

RUN chmod +x /app/DahuaVTO.py

ENTRYPOINT ["python3", "/app/DahuaVTO.py"]
```

 the output seems all goods:
>  ---> Running in 8ff3a01be36e
> Removing intermediate container 8ff3a01be36e
>  ---> d538e760b145
> Successfully built d538e760b145
> Successfully tagged dahuavto2mqtt:latest

and creating the container seems to be all ok...

**Comment by elad-bar** [comment]
You don't need to build the container just to run it, it will automatically pull it from Docker Hub,
I suggest to use the docker compose
