### ISSUE TITLE
asyncio socket.send() raised exception in version 1.0.12

### ISSUE THREAD

**Issue by Warmaker-be** [elad-bar/DahuaVTO2MQTT#27]
@elad-bar the problem isn't solved with your update. I'm still receiving 'WARNING asyncio socket.send() raised exception.' with version 1.0.12. this is after the mandatory mainentance restart of the VTO.
![image](https://user-images.githubusercontent.com/57051668/105711178-7a430b00-5f18-11eb-9dc3-94a0a418faa7.png)

**Comment by markverg** [comment]
hard to tell what version I'm running as versions are not tagged, but mine is 10 days old so it's probably
2021-Jan-15. There the doorbell keeps working after maintenance, but I also get these errors still.

@elad-bar it is possible to tag versions, so we can keep track of what we're running?

**Comment by elad-bar** [comment]
This is the repo of the docker, in case there is an issue with the addon, please open it there,
In addition,  please try to remove and reinstall it should solve the issue

**Comment by Warmaker-be** [comment]
@elad-bar sorry, i will post in the correct repo. 
btw, the reinstallation worked, thank you

**Comment by elad-bar** [comment]
np, thanks for the update
