### ISSUE TITLE
Hikvision integration

### ISSUE THREAD

**Issue by pepsonEL** [elad-bar/DahuaVTO2MQTT#32]
Hi. I see that you write good integration for Dauhua, Is any chance to also write this integration for Video Intecom Hikvision geneartion 1  model: DS-KV8102-IM with LCD touch panel DS-KH8301-WT ? Please maybe anybody help users Hikvision....

**Comment by pepsonEL** [comment]
halo halo.... are you there :)

**Comment by elad-bar** [comment]
Hi, sorry for the late response, 
Integration made for Dahua product as I own it, if you will find someone that owns it and forking that branch helps, go for it,
Sorry that I couldn't help more than that
