### ISSUE TITLE
Integrating Dahua IP cameras

### ISSUE THREAD

**Issue by avico78** [elad-bar/DahuaVTO2MQTT#39]
It would be really awesome if an integration with dahaua cameras will be added, 

there is other dahua2mqtt project which provide solution for dahua cameraa:
https://github.com/algirdasc/appdaemon-apps/blob/master/dahua_mqtt.py

 which working with apdaemon and it covers most of Dahua ivs functionalities ,maybe some can take a look and see if it be reuse to this project,a single running docker which give full cover for Dahua cameras and vto would be awesome :)

**Comment by elad-bar** [comment]
great idea, will check it in the upcoming weeks (overloaded at work :))

thanks!

**Comment by avico78** [comment]
> great idea, will check it in the upcoming weeks (overloaded at work :))
> 
> thanks!

happy u see interest it , a stand alone docker which handle both cameras and VTO in one places is a serious enhancement than for solution exists for Dahua, actually for the cameras  (the link i mention in top message) is actually best exists as it intrergearted with Home assistant ,support IVS events , the annoying side of it - u need Appdemon running for it.

**Comment by elad-bar** [comment]
ok... that was easy, it's already supported, use the `DAHUA_VTO_*` parameters of docker for the camera details,
Per camera that you are connecting, i suggest to use different MQTT topic prefix (`MQTT_BROKER_TOPIC_PREFIX`) and it should work, below events sent by MQTT for the camera:

```json
{
    "Action": "Start",
    "Code": "RtspSessionDisconnect",
    "Data": {
        "Device": "::ffff:x.x.x.x",
        "StreamType": "Main",
        "UTC": 1619275203.0,
        "UserAgent": " Lavf57.83.100"
    },
    "Index": 0,
    "Param": null,
    "deviceType": "IPC-HDBW4431R-ZS",
    "serialNumber": "xxxxxxx"
}
```

```json
{
    "Action": "State",
    "Code": "VideoMotionInfo",
    "Data": [
        {
            "Id": 0,
            "Region": [
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            "RegionName": "Region1",
            "State": "Inactive",
            "Threshold": 0
        }
    ],
    "Index": 0,
    "deviceType": "IPC-HDBW4431R-ZS",
    "serialNumber": "xxxxxxx"
}
```

```json
{
    "Action": "Stop",
    "Code": "VideoMotion",
    "Data": {
        "MachineName": "xxxxxx",
        "Name": "xxxxx",
        "RegionName": [
            "Region1"
        ],
        "UTC": 1619275453.0
    },
    "Index": 0,
    "deviceType": "IPC-HDBW4431R-ZS",
    "serialNumber": "xxxxxx"
}
```

**Comment by HappySl0th** [comment]
Will this work with the Hassio-addons branch you have?

**Comment by elad-bar** [comment]
yes, it's just a wrapper
