### ISSUE TITLE
Invalid syntax in DahuaVTO.py line 117

### ISSUE THREAD

**Issue by rostikk80** [elad-bar/DahuaVTO2MQTT#41]
SyntaxError: invalid syntax
    File "/app/DahuaVTO.py", line 117
    else if rc == 1:

**Comment by 8eholder** [comment]
Same problem with docker version. I´ve tried with anonymous and user and pass auth, network host and bridge.

**Comment by pilurizzu** [comment]
SyntaxError: invalid syntax
[cmd] /bin/ash exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
