### ISSUE TITLE
How to add multiple intercoms 

### ISSUE THREAD

**Issue by hasan-fardan** [elad-bar/DahuaVTO2MQTT#46]
I Have a VTO doorbell and face recognition access control. I want to configure both of these devices together. I tried configuring one device at a time; both devices are supported. So I tried to configure both devices to run together but it didn't work. These are the two configurations I tried:

configuration 1.

intercom:
  -   host: 192.168.1.184
      username: 
      password: 
  -   host: 192.168.1.183
      username: 
      password: 
mqtt:
  host: core-mosquitto
  port: '1883'
  username: 
  password: ''
  topic_prefix: DahuaVTO

configuration 2.

intercom:
  -   host: 192.168.1.184
      username: 
      password: 
  -   host: 192.168.1.183
      username: 
      password: 
mqtt:
  - host: core-mosquitto
    port: '1883'
    username: 
    password: ''
    topic_prefix: DahuaVTO
  - host: core-mosquitto
    port: '1883'
    username: 
    password: ''
    topic_prefix: DahuaASI

I get this error:
Failed to save add-on configuration, Invalid dict for option 'intercom' in DahuaVTO2MQTT (26703e67_dahuavto2mqtt).

**Comment by elad-bar** [comment]
It's not supported, you can define just one with the addon or create multiple containers for multiple devices.

Anyway, to avoid issues please follow the instructions
