### ISSUE TITLE
QUESTION: VTO2202F-P-S2 supported?

### ISSUE THREAD

**Issue by davidrustingha** [elad-bar/DahuaVTO2MQTT#52]
Since the VTO2202F-P isn't available in the Netherlands as standalone unit, i've been looking at a similar model named VTO2202F-P-S2.

I have seen one issue from a user who said that he had a specific issue with the repo and his S2 model, but haven't found a definitive answer if it works or not.

If you say it should work, I am willing to buy it and test some stuff out.

Thanks!

**Comment by davidrustingha** [comment]
Sorry, closed on accident..

**Comment by krasoff** [comment]
@davidrustingha yep. I've just tested it with my DHI-VTO2202F-P-S2 (fw 4.511.0000000.0.R, Build Date 2022-01-05)
