### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ivanaragom** [elad-bar/DahuaVTO2MQTT#54]
Hi!!

When i try to install the addon, see this error

The command '/bin/ash -o pipefail -c apk update && apk upgrade && apk add --no-cache python3 py3-pip py3-setuptools git && pip3 install --upgrade pip --no-cache-dir paho-mqtt requests' returned a non-zero code

I try to install in a new clean HA 8.4, but I reciver the same error

![image](https://user-images.githubusercontent.com/54279975/186153279-e3d5b315-9526-4c75-859d-3781ec5fb568.png)

**Comment by duca2** [comment]
same problem !!!!!!!!

**Comment by elad-bar** [comment]
Please read the manual on the main page!
