### ISSUE TITLE
Missing repository 

### ISSUE THREAD

**Issue by bennyboom38** [elad-bar/DahuaVTO2MQTT#6]
Hello
I try to add my video door bell Dahua by following this HowTo guide from video  https://www.youtube.com/watch?v=1U6SQDU6f24&t=262s
It's asking to install repository : https://github.com/elad-bar/Hassio-addons but it returns a 404 error page

Could you bring back this project please?

Thanks a lot

Ben

**Comment by elad-bar** [comment]
Hi, the video wasn't prepared by me and I removed the support for hassio addon as I'm using docker version of HA,
The version I support is docker based, instructions are in the readme file

**Comment by Duc1198** [comment]
ignore the email I send as well elad-bar was having the same issue.

**Comment by elad-bar** [comment]
@Duc1198 @bennyboom38 restored repo
