### ISSUE TITLE
Ssidnotvalid eror

### ISSUE THREAD

**Issue by aleksandryants** [elad-bar/DahuaVTO2MQTT#7]
MQTT message published, Topic: domofon/APConnect/Event, Payload: {"Action":"Stop","Data":{"Error":"SSIDNotValid","LocaleTime":"2020-09-11 18:19:55","Result":false,"UTC":1599837595}} 

I get this when I start dahuatomqtt
It start and then stops right away and gives this 

Thanks for help

**Comment by elad-bar** [comment]
SSIDNotValid is an issue that being thrown by your unit, nothing the integration can do with it,
is there any log message on top of that?

**Comment by elad-bar** [comment]
@aleksandryants, any updates?

**Comment by aleksandryants** [comment]
This error was send because device was not connected to WiFi ( and WiFi was turned on in the setting).
I used Poe connection so WiFi should been off

**Comment by elad-bar** [comment]
Can I close this issue?

**Comment by elad-bar** [comment]
@aleksandryants is it working for you? Can I close the issue?

Thanks
