### ISSUE TITLE
HassOS Pi3 installation fail

### ISSUE THREAD

**Issue by GerhardFreiberg** [elad-bar/DahuaVTO2MQTT#8]
Container logs:
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by elad-bar** [comment]
can you provide more details? how do you run it?

**Comment by elad-bar** [comment]
@GerhardFreiberg xan I close this issue?

Thanks

**Comment by IskenderKarfakis** [comment]
Hi,
I'm getting the same error on my Raspberry 4 with Hassos 5.2
Home Assistant : 0.116.4
os_name : Linux
os_version : 4.19.127-v8
python_version : 3.8.5
supervisor : 249
docker_version : 19.03.11

Setup via Portainer with the web editor data below:

version: '2'
services:
  dahuavto2mqtt:
    image: "eladbar/dahuavto2mqtt:latest"
    container_name: "dahuavto2mqtt"
    hostname: "dahuavto2mqtt"
    restart: always
    environment:
      - DAHUA_VTO_HOST=192.168.1.111
      - DAHUA_VTO_USERNAME=admin
      - DAHUA_VTO_PASSWORD=xxxxxxx
      - MQTT_BROKER_HOST=192.168.1.139
      - MQTT_BROKER_PORT=1883
      - MQTT_BROKER_USERNAME=admin
      - MQTT_BROKER_PASSWORD=xxxxxxx
      - MQTT_BROKER_TOPIC_PREFIX=DahuaVTO

The container deploys but getting the error "standard_init_linux.go:211: exec user process caused "exec format error" in the logs. Th container get stuck in an endless loop restarting.
