### ISSUE TITLE
Fatal Error on Start up (raspberrypi4-64)

### ISSUE THREAD

**Issue by IskenderKarfakis** [elad-bar/DahuaVTO2MQTT#9]
Hi,

The addon works fine on my tinker board. However on my new Raspberry 4 I get the following log:
(The mqtt server is up and running in the rasp 4)

Any ideas ?

"

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 00-banner.sh: executing... 
> -----------------------------------------------------------
>  Add-on: DahuaVTO2MQTT
>  Listens to events from Dahua VTO unit and publishes them via MQTT Message
> -----------------------------------------------------------
>  Add-on version: 1.0.5
>  There is an update available for this add-on!
>  Latest add-on version: null
>  Please consider upgrading as soon as possible.
> parse error: Expected string key before ':' at line 1, column 4
> [23:18:15] ERROR: Unknown HTTP error occured
>  System:   (aarch64 / raspberrypi4-64)
>  Home Assistant Core: 0.116.2
>  Home Assistant Supervisor: 247
> -----------------------------------------------------------
>  Please, share the above information when looking for help
>  or support in, e.g., GitHub, forums or the Discord chat.
> -----------------------------------------------------------
> [cont-init.d] 00-banner.sh: exited 0.
> [cont-init.d] 01-log-level.sh: executing... 
> [cont-init.d] 01-log-level.sh: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [23:18:17] INFO: Staring Dahua to MQTT
> <*** Dahua VTO Event Listener START ***>
> PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /app/DahuaVTO.php:492
> Stack trace:
> #0 /app/DahuaVTO.php(46): DahuaVTOEventListener->SetDeviceDetails()
> #1 /app/DahuaVTO.php(42): DahuaVTOEventListener->init_mqtt()
> #2 /app/DahuaVTO.php(8): DahuaVTOEventListener->DahuaVTOEventListener()
> #3 {main}
>   thrown in /app/DahuaVTO.php on line 492
> [cmd] /bin/ash exited 255
> [cont-finish.d] executing container finish scripts...
> [cont-finish.d] 99-message.sh: executing... 
> -----------------------------------------------------------
>                 Oops! Something went wrong.
> 
>  We are so sorry, but something went terribly wrong when
>  starting or running this add-on.
>  
>  Be sure to check the log above, line by line, for hints.
> -----------------------------------------------------------
> [cont-finish.d] 99-message.sh: exited 0.
> [cont-finish.d] done.
> [s6-finish] waiting for services.
> [s6-finish] sending all processes the TERM signal.

"

**Comment by elad-bar** [comment]
Did you install it as docker container or hassio addon?

Thanks

**Comment by IskenderKarfakis** [comment]
As a hassio Addon.
And when I install it as a Docker via Portainer I get the following message:
"standard_init_linux.go:211: exec user process caused "exec format error""

Thank you.

**Comment by mmnpkf** [comment]
I’m getting a similar error running as an add on after updating to version 1.0.6. Restoring the previous version doesn’t resolve the problem strangely. 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 

-----------------------------------------------------------
 Add-on: DahuaVTO2MQTT
 Listens to events from Dahua VTO unit and publishes them via MQTT Message
-----------------------------------------------------------
 Add-on version: 1.0.6
 There is an update available for this add-on!
 Latest add-on version: null
 Please consider upgrading as soon as possible.
parse error: Expected string key before ':' at line 1, column 4
[21:05:40] ERROR: Unknown HTTP error occured
 System:   (amd64 / qemux86-64)
 Home Assistant Core: 0.116.4
 Home Assistant Supervisor: 249
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:05:42] INFO: Staring Dahua to MQTT
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /app/DahuaVTO.php:79
Stack trace:
#0 /app/DahuaVTO.php(150): DahuaVTOAPI->SetDeviceDetails()
#1 /app/DahuaVTO.php(9): DahuaVTOEventListener->DahuaVTOEventListener()
#2 {main}
  thrown in /app/DahuaVTO.php on line 79
<*** Dahua VTO Event Listener START ***>
[cmd] /bin/ash exited 255
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by elad-bar** [comment]
This issure is related to the addon, please open it in the right repo:
https://github.com/elad-bar/Hassio-addons

Thanks
